/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

// import OOP
import Core.Human;

/**
 *
 * @author Prio
 */
public class CinemaSeats extends javax.swing.JFrame {
// inisiasi human
 Human human = new Human();
    /**
     * Creates new form CinemaSeats
     */
    public CinemaSeats() {
        initComponents();
    }

    // Validation
     private String validation(){
        List<String> flag = new ArrayList<String>();
        String alert = "";
    
    // validasi kursi studio
        if(!(cb_a1.isSelected())||
        (cb_a2.isSelected())||
        (cb_a3.isSelected())||
        (cb_a4.isSelected())||
        (cb_a5.isSelected())||
        (cb_a6.isSelected())||
        (cb_b1.isSelected())||
        (cb_b2.isSelected())||
        (cb_b3.isSelected())||
        (cb_b4.isSelected())||
        (cb_b5.isSelected())||
        (cb_b6.isSelected())||
        (cb_c1.isSelected())||
        (cb_c2.isSelected())||
        (cb_c3.isSelected())||
        (cb_c4.isSelected())||
        (cb_c5.isSelected())||
        (cb_c6.isSelected()) )
        {
        flag.add("Please select the seats!");
    }   

            if(flag.size() > 0)
        if (flag.size() > 0) {
            for (String msg : flag) {
                alert += (msg + "\n");
            }
        }
        return alert; 
}

    // reset form
    private void clearOptions ()   
{ 
    cb_a1.setSelected(false);
    cb_a2.setSelected(false);
    cb_a3.setSelected(false);
    cb_a4.setSelected(false);  
    cb_a5.setSelected(false);
    cb_a6.setSelected(false);
    cb_b1.setSelected(false);
    cb_b2.setSelected(false);
    cb_b3.setSelected(false);
    cb_b4.setSelected(false);
    cb_b5.setSelected(false);  
    cb_b6.setSelected(false);
    cb_c1.setSelected(false);
    cb_c2.setSelected(false);
    cb_c3.setSelected(false);
    cb_c4.setSelected(false);
    cb_c5.setSelected(false);  
    cb_c6.setSelected(false);
 
    label_result.setText("Your data hase been reset.");
}

    // save form
    private void saveForm()   
{ 
     String seats = null;
     if(cb_a1.isSelected()){
       seats = cb_a1.getText();
    }
     if(cb_a2.isSelected()){
       seats = cb_a2.getText();
    }
     if(cb_a3.isSelected()){
       seats =cb_a3.getText();
    }
     if(cb_a4.isSelected()){
       seats = cb_a4.getText();
    }
     if(cb_a5.isSelected()){
       seats = cb_a5.getText();
    }
     if(cb_a6.isSelected()){
       seats = cb_a6.getText();
    }
     if(cb_b1.isSelected()){
       seats = cb_b1.getText();
    }
     if(cb_b2.isSelected()){
       seats = cb_b2.getText();
    }
     if(cb_b3.isSelected()){
       seats = cb_b3.getText();
    }
     if(cb_b4.isSelected()){
       seats = cb_b4.getText();
    }
     if(cb_b5.isSelected()){
       seats = cb_b5.getText();
    }
     if(cb_b6.isSelected()){
       seats = cb_b6.getText();
    }
     if(cb_c1.isSelected()){
       seats = cb_c1.getText();
    }
     if(cb_c2.isSelected()){
       seats = cb_c2.getText();
    }
     if(cb_c3.isSelected()){
       seats = cb_c3.getText();
    }
     if(cb_c4.isSelected()){
       seats = cb_c4.getText();
    }
     if(cb_c5.isSelected()){
       seats = cb_c5.getText();
    }
     if(cb_c6.isSelected()){
       seats = cb_c6.getText();
    }
    // save oop
     this.human.setSeats(seats);

    // text area performance
//     int lines = ta_seats.getLineCount();
//     ta_seats.setText(Integer.toString(lines));
     ta_seats.(seats);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox8 = new javax.swing.JCheckBox();
        cb_a1 = new javax.swing.JCheckBox();
        cb_a2 = new javax.swing.JCheckBox();
        cb_a3 = new javax.swing.JCheckBox();
        cb_a4 = new javax.swing.JCheckBox();
        cb_a5 = new javax.swing.JCheckBox();
        cb_a6 = new javax.swing.JCheckBox();
        cb_b1 = new javax.swing.JCheckBox();
        cb_b2 = new javax.swing.JCheckBox();
        cb_b4 = new javax.swing.JCheckBox();
        cb_c6 = new javax.swing.JCheckBox();
        cb_b5 = new javax.swing.JCheckBox();
        cb_c1 = new javax.swing.JCheckBox();
        cb_b3 = new javax.swing.JCheckBox();
        cb_b6 = new javax.swing.JCheckBox();
        cb_c2 = new javax.swing.JCheckBox();
        cb_c4 = new javax.swing.JCheckBox();
        cb_c3 = new javax.swing.JCheckBox();
        cb_c5 = new javax.swing.JCheckBox();
        bt_save = new javax.swing.JButton();
        bt_reset = new javax.swing.JButton();
        label_studio = new javax.swing.JLabel();
        bt_next = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        label_result = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_seats = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox8.setText("jCheckBox8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        cb_a1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_a1.setForeground(new java.awt.Color(255, 255, 255));
        cb_a1.setText("A1");
        cb_a1.setContentAreaFilled(false);
        cb_a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_a1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb_a1);
        cb_a1.setBounds(91, 129, 70, 47);

        cb_a2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_a2.setForeground(new java.awt.Color(255, 255, 255));
        cb_a2.setText("A2");
        cb_a2.setContentAreaFilled(false);
        cb_a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_a2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb_a2);
        cb_a2.setBounds(176, 129, 80, 47);

        cb_a3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_a3.setForeground(new java.awt.Color(255, 255, 255));
        cb_a3.setText("A3");
        cb_a3.setContentAreaFilled(false);
        getContentPane().add(cb_a3);
        cb_a3.setBounds(261, 129, 90, 47);

        cb_a4.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_a4.setForeground(new java.awt.Color(255, 255, 255));
        cb_a4.setText("A4");
        cb_a4.setContentAreaFilled(false);
        getContentPane().add(cb_a4);
        cb_a4.setBounds(414, 129, 80, 47);

        cb_a5.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_a5.setForeground(new java.awt.Color(255, 255, 255));
        cb_a5.setText("A5");
        cb_a5.setContentAreaFilled(false);
        getContentPane().add(cb_a5);
        cb_a5.setBounds(511, 129, 80, 47);

        cb_a6.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_a6.setForeground(new java.awt.Color(255, 255, 255));
        cb_a6.setText("A6");
        cb_a6.setContentAreaFilled(false);
        getContentPane().add(cb_a6);
        cb_a6.setBounds(607, 129, 80, 47);

        cb_b1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_b1.setForeground(new java.awt.Color(255, 255, 255));
        cb_b1.setText("B1");
        cb_b1.setContentAreaFilled(false);
        getContentPane().add(cb_b1);
        cb_b1.setBounds(90, 214, 80, 47);

        cb_b2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_b2.setForeground(new java.awt.Color(255, 255, 255));
        cb_b2.setText("B2");
        cb_b2.setContentAreaFilled(false);
        getContentPane().add(cb_b2);
        cb_b2.setBounds(176, 214, 80, 47);

        cb_b4.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_b4.setForeground(new java.awt.Color(255, 255, 255));
        cb_b4.setText("B4");
        cb_b4.setContentAreaFilled(false);
        getContentPane().add(cb_b4);
        cb_b4.setBounds(414, 214, 90, 47);

        cb_c6.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_c6.setForeground(new java.awt.Color(255, 255, 255));
        cb_c6.setText("C6");
        cb_c6.setContentAreaFilled(false);
        getContentPane().add(cb_c6);
        cb_c6.setBounds(607, 304, 80, 47);

        cb_b5.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_b5.setForeground(new java.awt.Color(255, 255, 255));
        cb_b5.setText("B5");
        cb_b5.setContentAreaFilled(false);
        getContentPane().add(cb_b5);
        cb_b5.setBounds(511, 214, 80, 47);

        cb_c1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_c1.setForeground(new java.awt.Color(255, 255, 255));
        cb_c1.setText("C1");
        cb_c1.setContentAreaFilled(false);
        getContentPane().add(cb_c1);
        cb_c1.setBounds(90, 304, 80, 47);

        cb_b3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_b3.setForeground(new java.awt.Color(255, 255, 255));
        cb_b3.setText("B3");
        cb_b3.setContentAreaFilled(false);
        getContentPane().add(cb_b3);
        cb_b3.setBounds(267, 214, 80, 47);

        cb_b6.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_b6.setForeground(new java.awt.Color(255, 255, 255));
        cb_b6.setText("B6");
        cb_b6.setContentAreaFilled(false);
        getContentPane().add(cb_b6);
        cb_b6.setBounds(607, 214, 90, 47);

        cb_c2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_c2.setForeground(new java.awt.Color(255, 255, 255));
        cb_c2.setText("C2");
        cb_c2.setContentAreaFilled(false);
        getContentPane().add(cb_c2);
        cb_c2.setBounds(176, 304, 80, 47);

        cb_c4.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_c4.setForeground(new java.awt.Color(255, 255, 255));
        cb_c4.setText("C4");
        cb_c4.setContentAreaFilled(false);
        getContentPane().add(cb_c4);
        cb_c4.setBounds(414, 304, 79, 47);

        cb_c3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_c3.setForeground(new java.awt.Color(255, 255, 255));
        cb_c3.setText("C3");
        cb_c3.setContentAreaFilled(false);
        getContentPane().add(cb_c3);
        cb_c3.setBounds(267, 304, 80, 47);

        cb_c5.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cb_c5.setForeground(new java.awt.Color(255, 255, 255));
        cb_c5.setText("C5");
        cb_c5.setContentAreaFilled(false);
        getContentPane().add(cb_c5);
        cb_c5.setBounds(511, 304, 80, 47);

        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });
        getContentPane().add(bt_save);
        bt_save.setBounds(200, 379, 70, 28);

        bt_reset.setText("Reset");
        bt_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resetActionPerformed(evt);
            }
        });
        getContentPane().add(bt_reset);
        bt_reset.setBounds(90, 379, 70, 28);

        label_studio.setText("                                                                              ");
        getContentPane().add(label_studio);
        label_studio.setBounds(261, 54, 244, 30);

        bt_next.setText("Next");
        getContentPane().add(bt_next);
        bt_next.setBounds(632, 509, 70, 28);

        bt_back.setText("Back");
        getContentPane().add(bt_back);
        bt_back.setBounds(90, 509, 80, 28);

        label_result.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        label_result.setForeground(new java.awt.Color(255, 255, 255));
        label_result.setText("      ");
        getContentPane().add(label_result);
        label_result.setBounds(90, 430, 250, 24);

        ta_seats.setColumns(20);
        ta_seats.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ta_seats.setRows(5);
        jScrollPane1.setViewportView(ta_seats);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(388, 370, 300, 98);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prio\\Downloads\\seats.png")); // NOI18N
        jLabel1.setText("              ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_a1ActionPerformed

    }//GEN-LAST:event_cb_a1ActionPerformed

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        String validation = this.validation();
        if(validation.length() > 0) {
            JOptionPane.showMessageDialog(null, validation, "Validation Error!", 
            JOptionPane.INFORMATION_MESSAGE);
            return;
        } 
        else {
            this.saveForm();
        }
    }//GEN-LAST:event_bt_saveActionPerformed

    private void bt_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resetActionPerformed
      this.clearOptions();
    }//GEN-LAST:event_bt_resetActionPerformed

    private void cb_a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_a2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CinemaSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CinemaSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CinemaSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CinemaSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CinemaSeats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_next;
    private javax.swing.JButton bt_reset;
    private javax.swing.JButton bt_save;
    private javax.swing.JCheckBox cb_a1;
    private javax.swing.JCheckBox cb_a2;
    private javax.swing.JCheckBox cb_a3;
    private javax.swing.JCheckBox cb_a4;
    private javax.swing.JCheckBox cb_a5;
    private javax.swing.JCheckBox cb_a6;
    private javax.swing.JCheckBox cb_b1;
    private javax.swing.JCheckBox cb_b2;
    private javax.swing.JCheckBox cb_b3;
    private javax.swing.JCheckBox cb_b4;
    private javax.swing.JCheckBox cb_b5;
    private javax.swing.JCheckBox cb_b6;
    private javax.swing.JCheckBox cb_c1;
    private javax.swing.JCheckBox cb_c2;
    private javax.swing.JCheckBox cb_c3;
    private javax.swing.JCheckBox cb_c4;
    private javax.swing.JCheckBox cb_c5;
    private javax.swing.JCheckBox cb_c6;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_result;
    private javax.swing.JLabel label_studio;
    private javax.swing.JTextArea ta_seats;
    // End of variables declaration//GEN-END:variables

}
