/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import Form.TickerOrder;
import Core.Human;

/**
 *
 * @author Prio
 */
public class Menu extends javax.swing.JFrame {
Human human = new Human();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ali = new javax.swing.JButton();
        btn_quiteplace = new javax.swing.JButton();
        btn_jujutsu = new javax.swing.JButton();
        btn_luca = new javax.swing.JButton();
        btn_spiderman = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_ali.setBackground(new java.awt.Color(255, 204, 204));
        btn_ali.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        btn_ali.setForeground(new java.awt.Color(51, 51, 51));
        btn_ali.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ali.setLabel("Ali & ratu ratu queens");
        btn_ali.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btn_ali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aliMouseClicked(evt);
            }
        });

        btn_quiteplace.setBackground(new java.awt.Color(255, 204, 204));
        btn_quiteplace.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn_quiteplace.setForeground(new java.awt.Color(51, 51, 51));
        btn_quiteplace.setText("A Quite Place 2");
        btn_quiteplace.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_quiteplace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quiteplace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quiteplaceMouseClicked(evt);
            }
        });

        btn_jujutsu.setBackground(new java.awt.Color(255, 204, 204));
        btn_jujutsu.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn_jujutsu.setForeground(new java.awt.Color(51, 51, 51));
        btn_jujutsu.setText("Jujutsu Kaisen 0");
        btn_jujutsu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_jujutsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jujutsuMouseClicked(evt);
            }
        });

        btn_luca.setBackground(new java.awt.Color(255, 204, 204));
        btn_luca.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_luca.setForeground(new java.awt.Color(51, 51, 51));
        btn_luca.setText("Luca");
        btn_luca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_luca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lucaMouseClicked(evt);
            }
        });

        btn_spiderman.setBackground(new java.awt.Color(255, 204, 204));
        btn_spiderman.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        btn_spiderman.setForeground(new java.awt.Color(51, 51, 51));
        btn_spiderman.setText("Spider-man : NWH");
        btn_spiderman.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_spiderman.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btn_spiderman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_spidermanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_ali, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85)
                            .addComponent(btn_quiteplace, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(btn_jujutsu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(btn_luca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95)
                            .addComponent(btn_spiderman, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_ali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_quiteplace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_jujutsu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(240, 240, 240)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_luca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_spiderman, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aliMouseClicked
        String film = btn_ali.getText();
        this.human.setTitle(film);

        TickerOrder to = new TickerOrder();
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_aliMouseClicked

    private void btn_quiteplaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quiteplaceMouseClicked
        String film = btn_quiteplace.getText();
        this.human.setTitle(film);

        TickerOrder to = new TickerOrder();
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_quiteplaceMouseClicked

    private void btn_jujutsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jujutsuMouseClicked
        String film = btn_jujutsu.getText();
        this.human.setTitle(film);

        TickerOrder to = new TickerOrder();
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_jujutsuMouseClicked

    private void btn_lucaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lucaMouseClicked
        String film = btn_luca.getText();
        this.human.setTitle(film);

        TickerOrder to = new TickerOrder();
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_lucaMouseClicked

    private void btn_spidermanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_spidermanMouseClicked
        String film = btn_spiderman.getText();
        this.human.setTitle(film);

        TickerOrder to = new TickerOrder();
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_spidermanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ali;
    private javax.swing.JButton btn_jujutsu;
    private javax.swing.JButton btn_luca;
    private javax.swing.JButton btn_quiteplace;
    private javax.swing.JButton btn_spiderman;
    // End of variables declaration//GEN-END:variables
}
