/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import Form.TickerOrder;
import Core.Human;
import Core.Studio1;
import Core.Studio2;
import Core.Studio3;
import Core.Studio4;
import Core.Studio5;
import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author Prio
 */
public class Menu extends javax.swing.JFrame {
Human human = new Human();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();

        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ali = new javax.swing.JButton();
        btn_quiteplace = new javax.swing.JButton();
        btn_jujutsu = new javax.swing.JButton();
        btn_luca = new javax.swing.JButton();
        btn_spiderman = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ali.setBackground(new java.awt.Color(255, 204, 204));
        btn_ali.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        btn_ali.setForeground(new java.awt.Color(51, 51, 51));
        btn_ali.setText("Ali & Ratu Ratu Queens");
        btn_ali.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ali.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btn_ali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aliMouseClicked(evt);
            }
        });
        btn_ali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ali, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 180, 40));

        btn_quiteplace.setBackground(new java.awt.Color(255, 204, 204));
        btn_quiteplace.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn_quiteplace.setForeground(new java.awt.Color(51, 51, 51));
        btn_quiteplace.setText("A Quite Place 2");
        btn_quiteplace.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_quiteplace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quiteplace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quiteplaceMouseClicked(evt);
            }
        });
        getContentPane().add(btn_quiteplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 160, 40));

        btn_jujutsu.setBackground(new java.awt.Color(255, 204, 204));
        btn_jujutsu.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn_jujutsu.setForeground(new java.awt.Color(51, 51, 51));
        btn_jujutsu.setText("Jujutsu Kaisen 0");
        btn_jujutsu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_jujutsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jujutsuMouseClicked(evt);
            }
        });
        getContentPane().add(btn_jujutsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 160, 40));

        btn_luca.setBackground(new java.awt.Color(255, 204, 204));
        btn_luca.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_luca.setForeground(new java.awt.Color(51, 51, 51));
        btn_luca.setText("Luca");
        btn_luca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_luca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lucaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_luca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 160, 40));

        btn_spiderman.setBackground(new java.awt.Color(255, 204, 204));
        btn_spiderman.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        btn_spiderman.setForeground(new java.awt.Color(51, 51, 51));
        btn_spiderman.setText("Spider-man : NWH");
        btn_spiderman.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_spiderman.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btn_spiderman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_spidermanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_spiderman, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, 160, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prio\\Downloads\\ali.jpg")); // NOI18N
        jLabel3.setText("              ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prio\\Downloads\\a quite place 2.jpg")); // NOI18N
        jLabel4.setText("         ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prio\\Downloads\\jujutsu kaisen 0.jpg")); // NOI18N
        jLabel2.setText("        ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prio\\Downloads\\luca.jpg")); // NOI18N
        jLabel5.setText("            ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prio\\Downloads\\spider-man.jpg")); // NOI18N
        jLabel6.setText("          ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prio\\Downloads\\menu.png")); // NOI18N
        jLabel1.setText("             ");
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aliMouseClicked
        // mengambil data film yang dipilih
        String film = btn_ali.getText();
        this.human.setTitle(film);
    
        // inisiasi kelas studio untuk menentukan studio
        Studio1 studio = new Studio1();
        String studio1 = studio.studio1();
        this.human.setStudio(studio1);

        // lanjurt ke halaman berikutnya
        new TickerOrder(this.human).show();
    }//GEN-LAST:event_btn_aliMouseClicked

    private void btn_quiteplaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quiteplaceMouseClicked
       // mengambil data film yang dipilih
        String film = btn_quiteplace.getText();
        this.human.setTitle(film);
    
        // inisiasi kelas studio untuk menentukan studio
        Studio2 studio = new Studio2();
        String studio2 = studio.studio2();
        this.human.setStudio(studio2);

        // lanjut ke halaman berikutnya
        new TickerOrder(this.human).show();
    }//GEN-LAST:event_btn_quiteplaceMouseClicked

    private void btn_jujutsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jujutsuMouseClicked
        // mengambil data film yang dipilih
        String film = btn_jujutsu.getText();
        this.human.setTitle(film);
    
        // inisiasi kelas studio untuk menentukan studio
        Studio3 studio = new Studio3();
        String studio3 = studio.studio3();
        this.human.setStudio(studio3);

        // lanjut ke halaman berikutnya
        new TickerOrder(this.human).show();
    }//GEN-LAST:event_btn_jujutsuMouseClicked

    private void btn_lucaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lucaMouseClicked
        // mengambil data film yang dipilih
        String film = btn_luca.getText();
        this.human.setTitle(film);
    
        // inisiasi kelas studio untuk menentukan studio
        Studio4 studio = new Studio4();
        String studio4 = studio.studio4();
        this.human.setStudio(studio4);

        // lanjut ke halaman berikutnya
        new TickerOrder(this.human).show();
    }//GEN-LAST:event_btn_lucaMouseClicked

    private void btn_spidermanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_spidermanMouseClicked
        // mengambil data film yang dipilih
        String film = btn_spiderman.getText();
        this.human.setTitle(film);
    
        // inisiasi kelas studio untuk menentukan studio
        Studio5 studio = new Studio5();
        String studio5 = studio.studio5();
        this.human.setStudio(studio5);

        // lanjut ke halaman berikutnya
        new TickerOrder(this.human).show();
    }//GEN-LAST:event_btn_spidermanMouseClicked

    private void btn_aliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ali;
    private javax.swing.JButton btn_jujutsu;
    private javax.swing.JButton btn_luca;
    private javax.swing.JButton btn_quiteplace;
    private javax.swing.JButton btn_spiderman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
