/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Core.Human;

/**
 *
 * @author Prio
 */
public class Output extends javax.swing.JFrame {

    /**
     * Creates new form Output
     */
     public Output() {
        initComponents();
        ta_output.setEditable(false);
        ta_output.setBorder(null);
    }
     
    Human human = new Human();

    public void Output(){
       
        ta_output.setText("Detail Transaction"
            + " "
            + human.getTitle()
            + "\n   Name            : " + human.getName()
            + "\n   Phone Number    : " + human.getPhone()
            + "\n   Tickets         : " + human.getAmount()
            + "\n   Day             : " + human.getDay()
            + "\n   Time            : " + human.getTime()
            + "\n   Payment Methods : " + human.getPayment()
            + "\n   Total Payment   : " + human.getTotal()
        );

        tf_studio.setText(human.getStudio());
        ta_seats.setText(human.getSeats());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ta_output = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        tf_studio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_seats = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ta_output.setColumns(20);
        ta_output.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ta_output.setRows(5);
        getContentPane().add(ta_output);
        ta_output.setBounds(90, 160, 352, 380);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 55)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILL PAYMENT");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 80, 390, 56);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STUDIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 150, 130, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEATS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 360, 120, 32);

        btn_exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(560, 580, 101, 37);

        tf_studio.setText("     ");
        getContentPane().add(tf_studio);
        tf_studio.setBounds(540, 190, 130, 130);

        ta_seats.setColumns(20);
        ta_seats.setRows(5);
        jScrollPane2.setViewportView(ta_seats);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(530, 410, 150, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prio\\Downloads\\bill.png")); // NOI18N
        jLabel4.setText("          ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Output().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ta_output;
    private javax.swing.JTextArea ta_seats;
    private javax.swing.JTextField tf_studio;
    // End of variables declaration//GEN-END:variables
}
