/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import Core.Human;
import java.util.ArrayList;
import java.util.List;
import Form.TickerOrder;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class Studio extends javax.swing.JFrame {
Human human = new Human();

    /**
     * Creates new form Studio
     */
    public Studio() {
        initComponents();
    }

private void back(){
    Studio studio = new Studio();
    Human human = new Human();
    studio.dispose();
    new TickerOrder().show();
}
    
    private String Validation(){
        List<String> flag = new ArrayList<String>();
        String alert = "";
    
    // validasi kursi studio
    if(!(btn_a1.isSelected())|
        (btn_a2.isSelected())|
        (btn_a3.isSelected())|
        (btn_a4.isSelected())|
        (btn_a5.isSelected())|
        (btn_a6.isSelected())|
        (btn_b1.isSelected())|
        (btn_b2.isSelected())|
        (btn_b3.isSelected())|
        (btn_b4.isSelected())|
        (btn_b5.isSelected())|
        (btn_b6.isSelected())|
        (btn_c1.isSelected())|
        (btn_c2.isSelected())|
        (btn_c3.isSelected())|
        (btn_c4.isSelected())|
        (btn_c5.isSelected())|
        (btn_c6.isSelected()) )
        {
        flag.add("Please select the seats!");
    }   

       // validasi seats dan amount
     String amount = this.human.getAmount().toString();
     int test = bg_seats.getButtonCount();
     String seats = Integer.toString(test);

    label_test.setText(test);

    if ((seats.equals(amount))){
        flag.add("Limit excedeed");
    }
        
        if(flag.size() > 0)
        if (flag.size() > 0) {
            for (String msg : flag) {
                alert += (msg + "\n");
            }
        }
        return alert; 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton7 = new javax.swing.JRadioButton();
        bg_seats = new javax.swing.ButtonGroup();
        btn_c1 = new javax.swing.JRadioButton();
        btn_b1 = new javax.swing.JRadioButton();
        btn_c2 = new javax.swing.JRadioButton();
        btn_b2 = new javax.swing.JRadioButton();
        btn_c3 = new javax.swing.JRadioButton();
        btn_c4 = new javax.swing.JRadioButton();
        btn_b3 = new javax.swing.JRadioButton();
        btn_b4 = new javax.swing.JRadioButton();
        btn_a1 = new javax.swing.JRadioButton();
        btn_a2 = new javax.swing.JRadioButton();
        btn_a3 = new javax.swing.JRadioButton();
        btn_a4 = new javax.swing.JRadioButton();
        btn_a6 = new javax.swing.JRadioButton();
        btn_c5 = new javax.swing.JRadioButton();
        btn_b5 = new javax.swing.JRadioButton();
        btn_c6 = new javax.swing.JRadioButton();
        btn_b6 = new javax.swing.JRadioButton();
        btn_a5 = new javax.swing.JRadioButton();
        btn_submit = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_save = new javax.swing.JLabel();
        label_test = new javax.swing.JLabel();

        jRadioButton7.setText("jRadioButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        btn_c1.setText("C1");
        btn_c1.setMaximumSize(new java.awt.Dimension(43, 25));
        btn_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_c1);
        btn_c1.setBounds(73, 188, 38, 18);

        btn_b1.setText("B1");
        btn_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_b1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_b1);
        btn_b1.setBounds(73, 251, 37, 18);

        btn_c2.setText("C2");
        btn_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_c2);
        btn_c2.setBounds(149, 188, 38, 18);

        btn_b2.setText("B2");
        btn_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_b2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_b2);
        btn_b2.setBounds(149, 251, 37, 18);

        btn_c3.setText("C3");
        btn_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_c3);
        btn_c3.setBounds(232, 188, 38, 18);

        btn_c4.setText("C4");
        btn_c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_c4);
        btn_c4.setBounds(467, 188, 38, 18);

        btn_b3.setText("B3");
        btn_b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_b3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_b3);
        btn_b3.setBounds(232, 251, 37, 18);

        btn_b4.setText("B4");
        btn_b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_b4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_b4);
        btn_b4.setBounds(467, 251, 37, 18);

        btn_a1.setText("A1");
        btn_a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_a1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_a1);
        btn_a1.setBounds(73, 308, 36, 18);

        btn_a2.setText("A2");
        btn_a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_a2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_a2);
        btn_a2.setBounds(150, 308, 36, 18);

        btn_a3.setText("A3");
        btn_a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_a3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_a3);
        btn_a3.setBounds(231, 308, 36, 18);

        btn_a4.setText("A4");
        btn_a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_a4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_a4);
        btn_a4.setBounds(467, 308, 36, 30);

        btn_a6.setText("A6");
        btn_a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_a6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_a6);
        btn_a6.setBounds(633, 310, 36, 18);

        btn_c5.setText("C5");
        btn_c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_c5);
        btn_c5.setBounds(552, 188, 38, 18);

        bg_seats.add(btn_b5);
        btn_b5.setText("B5");
        btn_b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_b5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_b5);
        btn_b5.setBounds(552, 251, 37, 18);

        btn_c6.setText("C6");
        btn_c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_c6);
        btn_c6.setBounds(634, 188, 38, 18);

        bg_seats.add(btn_b6);
        btn_b6.setText("B6");
        btn_b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_b6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_b6);
        btn_b6.setBounds(634, 251, 37, 18);

        btn_a5.setText("A5");
        btn_a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_a5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_a5);
        btn_a5.setBounds(551, 310, 36, 18);

        btn_submit.setText("SAVE");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit);
        btn_submit.setBounds(610, 360, 58, 28);

        btn_next.setText("NEXT");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        getContentPane().add(btn_next);
        btn_next.setBounds(609, 455, 59, 28);

        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(73, 455, 60, 28);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAYAR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 60, 260, 60);

        label_save.setText("            ");
        getContentPane().add(label_save);
        label_save.setBounds(531, 400, 130, 16);

        label_test.setText("jLabel2");
        getContentPane().add(label_test);
        label_test.setBounds(190, 380, 100, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setLabel(){
     String seats = null;
     if(btn_a1.isSelected()){
       seats = btn_a1.getText();
     }
     if(btn_a2.isSelected()){
       seats = btn_a2.getText();
     }
     if(btn_a3.isSelected()){
       seats =btn_a3.getText();
     }
     if(btn_a4.isSelected()){
       seats = btn_a4.getText();
     }
     if(btn_a5.isSelected()){
       seats = btn_a5.getText();
     }
     if(btn_a6.isSelected()){
       seats = btn_a6.getText();
     }
     if(btn_b1.isSelected()){
       seats = btn_b1.getText();
     }
     if(btn_b2.isSelected()){
       seats = btn_b2.getText();
     }
     if(btn_b3.isSelected()){
       seats = btn_b3.getText();
     }
     if(btn_b4.isSelected()){
       seats = btn_b4.getText();
     }
     if(btn_b5.isSelected()){
       seats = btn_b5.getText();
     }
     if(btn_b6.isSelected()){
       seats = btn_b6.getText();
     }
     if(btn_c1.isSelected()){
       seats = btn_c1.getText();
     }
     if(btn_c2.isSelected()){
       seats = btn_c2.getText();
     }
     if(btn_c3.isSelected()){
       seats = btn_c3.getText();
     }
     if(btn_c4.isSelected()){
       seats = btn_c4.getText();
     }
     if(btn_c5.isSelected()){
       seats = btn_c5.getText();
     }
     if(btn_c6.isSelected()){
       seats = btn_c6.getText();
     }
    label_save.setText(seats);
}
    private void btn_b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_b4ActionPerformed
        
    }//GEN-LAST:event_btn_b4ActionPerformed

    private void btn_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_c5ActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        String validation = this.Validation();
        if(validation.length() > 0) {
            JOptionPane.showMessageDialog(null, validation, "Validation Error!", 
            JOptionPane.INFORMATION_MESSAGE);
            return;
        } 
        else {
          this.setLabel();
          
        }
        
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_a1ActionPerformed

    private void btn_a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_a2ActionPerformed

    private void btn_a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_a3ActionPerformed

    private void btn_a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_a4ActionPerformed

    private void btn_a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_a5ActionPerformed

    private void btn_a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_a6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_a6ActionPerformed

    private void btn_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_b1ActionPerformed

    private void btn_b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_b2ActionPerformed

    private void btn_b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_b3ActionPerformed

    private void btn_b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_b5ActionPerformed

    private void btn_b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_b6ActionPerformed

    private void btn_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_c1ActionPerformed

    private void btn_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_c2ActionPerformed

    private void btn_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_c3ActionPerformed

    private void btn_c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_c4ActionPerformed

    private void btn_c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_c6ActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
         this.next();
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.back();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_seats;
    private javax.swing.JRadioButton btn_a1;
    private javax.swing.JRadioButton btn_a2;
    private javax.swing.JRadioButton btn_a3;
    private javax.swing.JRadioButton btn_a4;
    private javax.swing.JRadioButton btn_a5;
    private javax.swing.JRadioButton btn_a6;
    private javax.swing.JRadioButton btn_b1;
    private javax.swing.JRadioButton btn_b2;
    private javax.swing.JRadioButton btn_b3;
    private javax.swing.JRadioButton btn_b4;
    private javax.swing.JRadioButton btn_b5;
    private javax.swing.JRadioButton btn_b6;
    private javax.swing.JButton btn_back;
    private javax.swing.JRadioButton btn_c1;
    private javax.swing.JRadioButton btn_c2;
    private javax.swing.JRadioButton btn_c3;
    private javax.swing.JRadioButton btn_c4;
    private javax.swing.JRadioButton btn_c5;
    private javax.swing.JRadioButton btn_c6;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JLabel label_save;
    private javax.swing.JLabel label_test;
    // End of variables declaration//GEN-END:variables

 }
